name: Deploy to Heroku

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -c "import app; print('✅ Application imports successfully')"
    
    - name: Test database initialization
      run: |
        python -c "
        from app import app, db
        with app.app_context():
            db.create_all()
            print('✅ Database initialization successful')
        "

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: "."
        healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/"
        checkstring: "Food Wastage Prediction"
        delay: 10
        procfile: "Procfile"
        buildpacks: |
          https://github.com/heroku/heroku-buildpack-python 